backend:
  name: github
  repo: bouncmpe/capstone-experimental
  auth_scope: public_repo
  branch: main
  open_authoring: true
publish_mode: editorial_workflow
media_folder: assets/images/uploads
public_folder: /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'offered'
    label: 'Project Offers'
    label_singular: 'Project Offer'
    folder: 'content/offered'
    create: true
    slug: '{{advisor}}-offer-{{title}}'
    editor:
      preview: false
    filter: {field: "type", value: "project-offer"}
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "project-offer"}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Advisor', 
          name: 'advisor', 
          widget: 'select', 
          multiple: true,
          options: [
            {label: "Advisor Name 1", value: "advisor.name.1"},
            {label: "Advisor Name 2", value: "advisor.name.2"},
            {label: "Advisor Name 3", value: "advisor.name.3"}
          ]
        }
      - { label: 'Tags', name: 'tags', widget: 'list', label_singular: 'tag', field: { label: "Tag", name: "tag", widget: "string" }}
      - { label: 'Abstract', name: 'body', widget: 'markdown', default: ''}


