backend:
  name: github
  repo: bouncmpe/capstone-experimental
  auth_scope: public_repo
  branch: main
  open_authoring: true

search: false
publish_mode: editorial_workflow
media_folder: assets/images/uploads
public_folder: /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'senior-project-offer'
    label: 'Senior Project Offers'
    label_singular: 'Senior Project Offer'
    folder: 'content/offers'
    create: true
    slug: '{{year}}-{{title}}'
    editor:
      preview: false
    filter: {field: "type", value: "senior-project-offer"}
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "senior-project-offer"}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Advisors', 
          name: 'authors', 
          widget: 'select', 
          multiple: true,
          options: ["Ozlem Durmaz Incel", "Dogan Ulus", "Suzan Uskudarli"]
        }
      - { label: 'Abstract', name: 'body', widget: 'markdown', default: ''}


