backend:
  name: github
  repo: bouncmpe/capstone-experimental
  auth_scope: public_repo
  branch: main
  open_authoring: true

search: false
publish_mode: editorial_workflow
media_folder: assets/images/uploads
public_folder: /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: 'offered'
    label: 'Project Offers'
    label_singular: 'Project Offer'
    folder: 'content/offered'
    create: true
    slug: '{{year}}-{{advisor}}-{{title}}'
    editor:
      preview: false
    filter: {field: "type", value: "project-offer"}
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "project-offer"}
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Advisor', 
          name: 'advisor', 
          widget: 'select', 
          multiple: true,
          options: ["Özlem Durmaz İncel", "Doğan Ulus", "Suzan Üsküdarlı"]
        }
      - { label: 'Tags', name: 'tags', widget: 'list', label_singular: 'tag', field: { label: "Tag", name: "tag", widget: "string" }}
      - { label: 'Abstract', name: 'body', widget: 'markdown', default: ''}


